# LambdaTest AI Cloud Configuration
project_id: "01KBGC958JZM0KS456TGE0BR36"
folder_id: "01KBGCNC0BBJMJ9FWWPNVJT586"
assignee: sriram@lambdatest.com
environment_id: 181620
test_url: "http://localhost:3000/"
